name: CI misc

on:
  push:
    branches:
      # Push events to branches matching refs/heads/main
      - 'main'
      # Push events to branches matching refs/heads/release*
      - 'release*'
  # Trigger after PR was unlabeled
  pull_request:
    types:
      - unlabeled
  # Enables a manual trigger, may run on any branch
  workflow_dispatch:

concurrency:
  group: misc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'clang-format'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Snippet gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build: snippet
            build_type: Release
            build_threads: 2
            test_threads: 1 # snippets create and delete files and some separate tests create/delete the same files
            cxx_flags: "-std=c++20"
            cmake: 3.16.9
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: false

          - name: "Header gcc12"
            cxx: "g++-12"
            cc: "gcc-12"
            build: header
            build_type: Debug
            build_threads: 2
            test_threads: 2
            cmake: 3.16.9
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: false

          - name: "Header gcc10"
            cxx: "g++-10"
            cc: "gcc-10"
            build: header
            build_type: Debug
            build_threads: 2
            test_threads: 2
            cmake: 3.16.9
            requires_toolchain: true
            requires_ccache: true
            skip_build_tests: false
            skip_run_tests: false

          - name: "Documentation"
            build: documentation
            build_threads: 2
            test_threads: 2
            cmake: 3.16.9
            doxygen: 1.9.7
            requires_toolchain: false
            requires_ccache: false
            skip_build_tests: true
            skip_run_tests: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: sharg
          fetch-depth: 1
          submodules: true

      # To reuse scripts
      - name: Checkout SeqAn3
        uses: actions/checkout@v3
        with:
          repository: seqan/seqan3
          ref: aa3df18a6df59679e07e9fe2de4e0998a94af7e7
          path: seqan3
          fetch-depth: 1
          submodules: false

      - name: Configure APT
        continue-on-error: true
        run: bash ./seqan3/.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        env:
          BUILD: ${{ matrix.build }}
          CMAKE_VERSION: ${{ matrix.cmake }}
        run: bash ./seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install Doxygen
        if: matrix.build == 'documentation'
        env:
          DOXYGEN_VERSION: ${{ matrix.doxygen }}
        run: bash ./seqan3/.github/workflows/scripts/install_doxygen.sh

      - name: Install ccache
        if: matrix.requires_ccache
        run: |
          conda install --yes --override-channels --channel conda-forge ccache
          sudo ln -s $CONDA/bin/ccache /usr/bin/ccache

      - name: Install compiler ${{ matrix.cxx }}
        if: matrix.requires_toolchain
        run: sudo apt-get install --yes ${{ matrix.cxx }}

      - name: Load ccache
        if: matrix.requires_ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env doxygen --version || true
          env ${{ matrix.cxx }} --version || true

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir sharg-build
          cd sharg-build
          cmake ../sharg/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                                  -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                                                  -DSHARG_VERBOSE_TESTS=OFF
          case "${{ matrix.build }}" in
            snippet) make -j${{ matrix.build_threads }} gtest_build yaml-cpp;;
            header) make -j${{ matrix.build_threads }} gtest_build gbenchmark_build yaml-cpp;;
            documentation) make -j${{ matrix.build_threads }} download-cppreference-doxygen-web-tag;;
          esac

      - name: Build tests
        if: ${{ !matrix.skip_build_tests }}
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 75M
        run: |
          ccache -z || true
          cd sharg-build
          make -k -j${{ matrix.build_threads }}
          ccache -sv || true

      - name: Run tests
        if: ${{ !matrix.skip_run_tests }}
        run: |
          cd sharg-build
          ctest . -j${{ matrix.test_threads }} --output-on-failure
